steps:
  - label: "CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating environment")
                Pkg.add("CUDA")
                Pkg.develop(PackageSpec(name="Atomix", path="."))

                println("+++ :julia: Running tests")
                Pkg.test()'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 15

  - label: "Metal.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating environment")
                Pkg.add("Metal")
                Pkg.develop(PackageSpec(name="Atomix", path="."))

                println("+++ :julia: Running tests")
                Pkg.test()'
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 15
